# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  secureFile: 'sebatestapi.usr'

steps:
- script: dotnet build --configuration $(buildConfiguration) ./src/TwitterLib.csproj
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration) ./tests/TwitterLibTests.csproj
  displayName: 'dotnet build $(buildConfiguration) (TEST)'

- task: DownloadSecureFile@1
  inputs:
    secureFile: $(secureFile)
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '$(secureFile)'
    TargetFolder: './test/bin/$(buildConfiguration)/netcoreapp2.2/Resources'

- script: dotnet test --no-build --configuration $(buildConfiguration) ./tests/TwitterLibTests.csproj
  displayName: 'Run tests ($(buildConfiguration))'
  env:
    VAULT_URL: $(vaultUrl)
    APPLICATION_ID: $(appId)
    APPLICATION_SECRET: $(appSecret)
- script: dotnet pack --no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) ./src/TwitterLib.csproj
  displayName: 'NuGet pack'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'nuget'