name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      VERBOSITY: normal

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Inject test credentials
      env:
        SEBA_TEST_API: ${{ secrets.SEBA_TEST_API }}
      run: echo $SEBA_TEST_API > ./tests/Resources/sebatestapi.data
    - name: Build
      run: dotnet build --no-restore --configuration $CONFIGURATION
    - name: Test
      run: dotnet test --no-build --verbosity $VERBOSITY --configuration $CONFIGURATION
    - name: Pack
      run: dotnet pack --no-build --configuration $CONFIGURATION --output ./bin ./src/TwitterLib.csproj
    - name: Push
      env:
        NUGET_KEY: ${{ secrets.TWITTERLIB_NUGET_KEY }}
      run: dotnet nuget push -s ./bin/*.nupkg -k $NUGET_KEY
    # - name: Publish NuGet
    #   env:
    #     NUGET_KEY: ${{ secrets.TWITTERLIB_NUGET_KEY }}
    #   uses: brandedoutcast/publish-nuget@v2.5.5
    #   with:
    #     # Filepath of the project to be packaged, relative to root of repository
    #     PROJECT_FILE_PATH: ./src/TwitterLib.csproj
    #     # API key to authenticate with NuGet server
    #     NUGET_KEY: $NUGET_KEY
